apiVersion: "v1"
kind: "Service"
metadata:
  name: "pdf-service-service"
  namespace: "default"
  labels:
    app: "pdf-service"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
      nodePort: 30001
  selector:
    app: "pdf-service"
  type: "LoadBalancer"
